In [29]:
import pandas as pd
from sentence_transformers import SentenceTransformer
import faiss
import joblib

In [8]:
df = pd.read_csv("tmdb_5000_movies.csv")

In [9]:
df.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='str')

In [12]:
df = df[['title', 'overview']]

In [13]:
df

,title,overview
0,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,Spectre,A cryptic message from Bond’s past sends him o...
3,The Dark Knight Rises,Following the death of District Attorney Harve...
4,John Carter,"John Carter is a war-weary, former military ca..."
...,...,...
4798,El Mariachi,El Mariachi just wants to play his guitar and ...
4799,Newlyweds,A newlywed couple's honeymoon is upended by th...
4800,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic..."
4801,Shanghai Calling,When ambitious New York attorney Sam is sent t...
4802,My Date with Drew,Ever since the second grade when he first saw ...

In [14]:
df.isnull().sum()

title       0
overview    3
dtype: int64

In [17]:
df.dropna(inplace=True)

In [19]:
df.duplicated().any()

np.False_

In [21]:
df.reset_index(drop=True)

,title,overview
0,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,Spectre,A cryptic message from Bond’s past sends him o...
3,The Dark Knight Rises,Following the death of District Attorney Harve...
4,John Carter,"John Carter is a war-weary, former military ca..."
...,...,...
4795,El Mariachi,El Mariachi just wants to play his guitar and ...
4796,Newlyweds,A newlywed couple's honeymoon is upended by th...
4797,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic..."
4798,Shanghai Calling,When ambitious New York attorney Sam is sent t...
4799,My Date with Drew,Ever since the second grade when he first saw ...

In [23]:
movies = df.overview.tolist()

In [24]:
type(movies)

list

In [26]:
model = SentenceTransformer("all-MiniLM-L6-v2")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [27]:
embeddings = model.encode(movies,show_progress_bar=True)

Batches:   0%|          | 0/150 [00:00<?, ?it/s]

In [28]:
embeddings.shape

(4800, 384)

In [30]:
dimension = embeddings.shape[1]
index = faiss.IndexFlatL2(dimension)
index.add(embeddings)

In [31]:
joblib.dump(df, "movies.pkl")
faiss.write_index(index, "movies.index")